Cabal GitHub action for GHC 9.2, 9.4, 9.6
haskell/stylish-haskell pull request #448
Opened 2023-03-05 23:45 UTC by peterbecich

2023-03-09 16:46 UTC, jaspervdj requested changes
Thanks for the PR!

2023-03-09 16:46 UTC, jaspervdj commented on .github/workflows/cabal.yml
> +    - name: Get the version
We probably don’t need this step

2023-03-09 16:46 UTC, jaspervdj commented on .github/workflows/cabal.yml
> +        path: ~/.stack
Path should likely be updated?

2023-03-09 16:46 UTC, jaspervdj commented on .github/workflows/cabal.yml
> +    - name: Build artifact
Everything below this is not needed I think

2023-03-10 05:41 UTC, peterbecich commented on .github/workflows/cabal.yml
> +    - name: Get the version
you're right, thanks

2023-03-10 08:41 UTC, jaspervdj approved these changes

2023-03-10 08:41 UTC, merged

2023-03-10 08:42 UTC, jaspervdj commented
Looking good now, thanks a lot!

2023-03-18 21:57 UTC, peterbecich commented
Thank you, @jaspervdj